### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by bhaktikhera1** [alvgaona/heart-sounds-segmentation#2]
Hello everyone! Your work is excellent, I was using the Metrics, may I ask what is the argument 'description'? I could not find anything. Also, I am new to MATLAB, how to use Metrics properly to get the results? I used it and it is giving me [] in all.
Thank you in advance.

**Comment by alvgaona** [comment]
Hi @bhaktikhera1. Metrics is a MATLAB class defined by this project. It is used as a simple class, you need to instantiate it and then use the methods. To instantiate it you just need the confusion matrix and a description of the object (not really needed in practice).

If you're new to MATLAB classes, check out [User-defined Classes](https://www.mathworks.com/help/matlab/matlab_oop/user-defined-classes.html).

**Comment by bhaktikhera1** [comment]
Hi, thanks a lot for your answer. Now, I got it!

**Comment by alvgaona** [comment]
No worries. Soon I'll have the version written in PyTorch, if you're interested.

**Comment by bhaktikhera1** [comment]
That would be great.

**Comment by alvgaona** [comment]
@bhaktikhera1 here's a[ preliminary branch](https://github.com/alvgaona/heart-sounds-segmentation/tree/torch) for the PyTorch implementation. Still working on it, but just for a preview.
